spring.application.name=api-inovacao


#Configuracao de Conexao com o Banco de Dados
spring.mongodb.uri=mongodb+srv://valltersouza_db_user:New2023@clusterfiap.rrkjvjw.mongodb.net/?appName=ClusterFiap
spring.mongodb.database=aguia_branca_db
api.security.token.secret=aguia-branca-secret-key-2026